### ISSUE TITLE
information on datasets

### ISSUE THREAD

**Issue by giovp** [QuKunLab/SpatialBenchmarking#10]
Hi,

thanks a lot for making code and data avialble for this benchmark, is very useful. I was wondering if you could provide more info on the datasets
![image](https://user-images.githubusercontent.com/25887487/179596752-6e4a44b1-2b3b-4299-8bb4-29bce9ec965f.png)

in particular, what's the difference between DataUpload and TestData ?

Thanks again!

**Comment by wenruyustc** [comment]
Hi~, you can get more information about 45 datsets from Supplementary Tables 1&2. (https://static-content.springer.com/esm/art%3A10.1038%2Fs41592-022-01480-9/MediaObjects/41592_2022_1480_MOESM4_ESM.xlsx)
And For test datasetes, we just uploaded the data that used in jupyter. 
We also have a README file for these files in data download web (https://drive.google.com/file/d/1jDjGbStWJA7OLqyMY0ameVYxLC5Z4vCh/view?usp=sharing).

**Comment by giovp** [comment]
thanks a lot @wenruyustc ! Is that correct that only the folder `SimualtedSpatalData` contains the data used for the deconvolution benchmark?

**Comment by wenruyustc** [comment]
Hi , yes, For fig4e, we only used data in folder SimualtedSpatalData for the deconvolution benchmark, and the 45 real datasets are used for gene prediction benchmark

**Comment by giovp** [comment]
that's great, thanks a lot for the prompt reply!
