### ISSUE TITLE
Ground truth of dataset4 in Figure4

### ISSUE THREAD

**Issue by lzygenomics** [QuKunLab/SpatialBenchmarking#11]
Hi~  @wenruyustc 

Thanks for your fancy work ! When I was processing the dataset4, I found that the annotation of scRNA-seq is unpaired with the annotation of spot clusters, so I could not calculate the measurement results~Would you mind sharing your specific alignment method ?

Best,
Zhiyuan Liu

**Comment by wenruyustc** [comment]
Hi~, if you are using Dataset 4 as an example, you can use BLAST_CelltypeDeconvolution.ipynb to simulate the spot and follow BLAST_CelltypeDeconvolution.ipynb to calculate the measurement results

**Comment by lzygenomics** [comment]
> Hi~, if you are using Dataset 4 as an example, you can use BLAST_CelltypeDeconvolution.ipynb to simulate the spot and follow BLAST_CelltypeDeconvolution.ipynb to calculate the measurement results

Thank you very much for your prompt reply! Maybe I didn't make it clear that Dataset 4 I said here refers to the dataset formed by drawing the grid, not the dataset4 in the simulation sets~ It seems that the script "BLAST_CelltypeDeconvolution.ipynb" didn't contain the information about Dataset 4's evaluation~

Thanks again~
Best

**Comment by wenruyustc** [comment]
Sorry for misunderstanding. In fact, we only used 8 paired cell clusters (Astro,	Endo,ExcitatoryL2and3,ExcitatoryL4,ExcitatoryL5and6,Inhibitory,Micro ,Olig) to evaluate the  evaluation prediction result. And other cell types, such as Ependymal or Neuroblast, are exclude from the evaluation.

**Comment by lzygenomics** [comment]
Ok~Thanks for your help!
