### ISSUE TITLE
PCC & SSIM in deconvoluting methods

### ISSUE THREAD

**Issue by lzygenomics** [QuKunLab/SpatialBenchmarking#3]
Hi~ 

Thanks for your nice work！ It's really fascinating~  I have a question about how to calculate the PCC and SSIM in deconvoluting methods~? The results of these methods seem just offer the proportions of cell types, so I wonder how to transfer proportion to genes expression ?  : ) 

Best wishes!

**Comment by wenruyustc** [comment]
Hi. For cell type deconvolution, we constructed 32 simulation datasets with known cell type distributions as ground truth (uns['density'] is the cell type composition of each spot for simulation datasets) to evaluate the performance of these algorithms. So for each datasets,  cell type composition of each spot by prediction can be used to calculate the correlation with cell type composition of each spot in ground truth.

**Comment by lzygenomics** [comment]
> Hi. For cell type deconvolution, we constructed 32 simulation datasets with known cell type distributions as ground truth (uns['density'] is the cell type composition of each spot for simulation datasets) to evaluate the performance of these algorithms. So for each datasets, cell type composition of each spot by prediction can be used to calculate the correlation with cell type composition of each spot in ground truth.

Thanks for your quickly reply~ It's really helpful !
