### ISSUE TITLE
scRNA-seq data of figure 4

### ISSUE THREAD

**Issue by lzygenomics** [QuKunLab/SpatialBenchmarking#4]
Hi~

Thank you for the nice work and especially the friendly code ! I wonder if could you please share the scRNA-seq matrix of Dataset10 ande Dataset 4 in figure 4 ? I find the single cell annotation and spatial data, but maybe not see the scRNA count matrix~

Best wishes !

**Comment by wenruyustc** [comment]
Hi ~
you can download the scRNA-seq matrix of Dataset10 and Dataset 4 from TestData.zip (https://drive.google.com/drive/folders/1pHmE9cg_tMcouV1LFJFtbyBJNp7oQo9J?usp=sharing)

**Comment by wenruyustc** [comment]
> > Hi ~ you can download the scRNA-seq matrix of Dataset10 and Dataset 4 from TestData.zip (https://drive.google.com/drive/folders/1pHmE9cg_tMcouV1LFJFtbyBJNp7oQo9J?usp=sharing)
> 
> Thanks for your quick reply ~! It seems that there is no TestData.zip in the link, maybe you mean Dataset10 and Dataset 4 from "DataUpload.zip" file ?

Sorry, I upload the TestData.zip  now, and Dataset10 and Dataset 4 from "DataUpload.zip" file is OK.

**Comment by lzygenomics** [comment]
> > > Hi ~ you can download the scRNA-seq matrix of Dataset10 and Dataset 4 from TestData.zip (https://drive.google.com/drive/folders/1pHmE9cg_tMcouV1LFJFtbyBJNp7oQo9J?usp=sharing)
> > 
> > 
> > Thanks for your quick reply ~! It seems that there is no TestData.zip in the link, maybe you mean Dataset10 and Dataset 4 from "DataUpload.zip" file ?
> 
> Sorry, I am uploading the TestData.zip now, and Dataset10 and Dataset 4 from "DataUpload.zip" file is OK.

So kind of you ! Thank you : )
