### ISSUE TITLE
Error in reproducing “Tutorial.ipynb”: deconvolution part

### ISSUE THREAD

**Issue by jiawei-zhong** [QuKunLab/SpatialBenchmarking#5]
Hi,

When I followed "Prediction Celltype deconvolution" part in Tutorial.ipynb. I met a problem:

```
Traceback (most recent call last):
  File "Codes/Deconvolution/DestVI_pipeline.py", line 52, in <module>
    scvi.data.setup_anndata(sc_adata, layer="counts", labels_key=celltype_key)
AttributeError: module 'scvi.data' has no attribute 'setup_anndata'
```

I observed that your code (in "Codes/Deconvolution/DestVI_pipeline.py") use "scvi.data.setup_anndata". However, this fuction is present at the old versions of scvi-tools (e.g. 0.8.0b0, which lack "DestVi" function) but absent in the new versions of scvi-tools (e.g. 0.15.3, which are required by Cell2location). It seems to be a contradiction. Could you please tell me the version of each package or just change the codes?

Thank you very much in advance!

**Comment by wenruyustc** [comment]
Hi~ Thanks for your suggestion!
In our paper, We used Cell2location(Version: 0.6a0) and DestVI(Version: 0.11.0).  We will update the codes later for new version.
