### ISSUE TITLE
Code for figure4c & 4d

### ISSUE THREAD

**Issue by lzygenomics** [QuKunLab/SpatialBenchmarking#6]
Hi~

Thanks for your detailed code , it's really friendly and powerful ! 
Could you please share the code to make the figure 4c and 4d~? ( which compute the **Accuracy Score** for dataset 10 and dataset 4 )~ And now I see the code for dataset 10 , if possible ~ could you share the code for dataset 4 as well ?  :  )  
Greatly appreciate your help !

Best wishes!

**Comment by wenruyustc** [comment]
Hi~
Thank you very much for your patience！
The STARmap_AS.ipynb file is our code from the prediction results to the final accuracy score. You can use it to implement the plot of Figure4c. 
At the same time, we provided the simulated spatial expression matrix of the dataset in the FigureData/Figure4/Dataset4_seqFISH+/Simulated_seqFISH+ file, which can be input into different tools for prediction. And You can compute the accuracy score for dataset 4 （Figure4d）by using the calculation method in STARmap_AS.ipyn
[STARmap_AS.ipynb.zip](https://github.com/QuKunLab/SpatialBenchmarking/files/8793670/STARmap_AS.ipynb.zip)
b

**Comment by lzygenomics** [comment]
> Hi~ I am sorry for for not being able to reply you in time due to holiday. Thank you very much for your patience！ The STARmap_AS.ipynb file is our code from the prediction results to the final accuracy score. You can use it to implement the plot of Figure4c. At the same time, we provided the simulated spatial expression matrix of the dataset in the FigureData/Figure4/Dataset4_seqFISH+/Simulated_seqFISH+ file, which can be input into different tools for prediction. And You can compute the accuracy score for dataset 4 （Figure4d）by using the calculation method in STARmap_AS.ipyn [STARmap_AS.ipynb.zip](https://github.com/QuKunLab/SpatialBenchmarking/files/8793670/STARmap_AS.ipynb.zip) b

Thank you very much ！It's really helpful ~! wish you all the best~
