### ISSUE TITLE
Still have error in reproducing “Tutorial.ipynb”: deconvolution part

### ISSUE THREAD

**Issue by jiawei-zhong** [QuKunLab/SpatialBenchmarking#7]
Hi, 
I observed that you have updated the codes. However, some problems have not been solved yet.
```
1) In "Codes/Deconvolution/Stereoscope_pipeline.py", Line 51: change "scvi.data.setup_anndata" to "RNAStereoscope.setup_anndata"
2) In "Codes/Deconvolution/Stereoscope_pipeline.py", Line 58: change "scvi.data.setup_anndata" to "SpatialStereoscope.setup_anndata"
3) In "Codes/Deconvolution/Cell2location_pipeline.py", Line 47: change "scvi.data.setup_anndata" to "cell2location.models.RegressionModel.setup_anndata"
4) In "Codes/Deconvolution/Cell2location_pipeline.py", Line 77: change "scvi.data.setup_anndata" to "cell2location.models.Cell2location.setup_anndata"
5) In "Codes/Deconvolution/Cell2location_pipeline.py", Line 78: mute it
6) In "doc/Tutorial.ipynb", change all "my_python_path" to "python_path" to let it be identical to "Benchmarking/DeconvolutionSpot.py"
7) In "Codes/Deconvolution/SpatialDWLS_pipeline.r", let output_path = args[5] and let my_python_path = args[4]. Just letting it be identical to "Benchmarking/DeconvolutionSpot.py"
8) "Codes/Deconvolution/DSTG_pipeline.r" is missing.
```

I am still tring to reproduce it and will pose bug to this if I meet.

I wish authors should provide every packages' versions, which will largely facility users to reproduce. For example, it seems that authors used a very old version of SPOTlight (from observing the code. The latest and the old versions of SPOTlight are totally different). However, users cannot repeat or successfully finish the tutorial if they follow the published article to install packages.

**Comment by wenruyustc** [comment]
Hi~  thank you so much for your suggestion! ! !
We used every packages' versions as: Cell2location(Version 0.6a0), DestVI (scvi-tools Version 0.11.0), Stereoscope (within the scvi-tools Version 0.11.0), Seurat(Version 4.0.5), RCTD(Version 1.2.0), SPOTlight(Version 0.1.7), SpatialDWLS(by Giotto of Version 1.0.4), Tangram(Version 1.0.0), STRIDE(Version 0.0.1b), DSTG(Version 0.0.1)
For DSTG, It is more easier to run by their github tutorial(https://github.com/Su-informatics-lab/DSTG). 
We will check and update the codes for new version later.
Thanks again!

**Comment by stupidstupidstupidstupid** [comment]
> 

May I ask you what Python version are you using? It seems that the scvi-tools in version 0.11.0 is conflict with Python 3.6.
