### ISSUE TITLE
Normalization is only for scRNA data

### ISSUE THREAD

**Issue by sinanugur** [QuKunLab/SpatialBenchmarking#9]
Hello,

It seems the normalization was only performed on scRNA data. Is there a special reason for that? For example, in Stereoscope pipeline:

https://github.com/QuKunLab/SpatialBenchmarking/blob/3586b9d81c479f939aa40adedfe1c95c5b496bcb/Codes/Deconvolution/Stereoscope_pipeline.py

Thanks.

**Comment by wenruyustc** [comment]
Hello, There is no special reason, we just followed the tutorial of each methods.

**Comment by sinanugur** [comment]
Thanks for your answer @wenruyustc
